### ISSUE TITLE
Error lnk2001: unresolved external symbol "public:static struct HINSTANCE_*_

### ISSUE THREAD

**Issue by valentindeian** [Vegas007/Metin2-Badge-Notification-Manager#4]
I think something is missing , I checked the files and they are all correct. When compiling I get this error:
[
![Untitled](https://user-images.githubusercontent.com/118624182/202861519-dfd02c17-c946-4f81-bd90-c81bb3c1e1c4.jpg)
](url)

**Comment by Vegas007** [comment]
Missing _ENABLE_BADGE_NOTIFICATION_MANAGER_ on EterLib/Stdafx.h
